//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/ct2JP.z64", "rom/ct2JP.mod.z64", 0 // Open the ROM file
.include "asm/symbols.asm" // Include ct2.asm to tell armips' linker where to find the game's function(s)
.headersize 0x7F800000
.org 0x80400000
.include "asm/bootPatch.asm"
.importobj "obj/crash.o"
.importobj "obj/lib.o"
.importobj "obj/lz4.o"
.importobj "obj/main.o"
.importobj "obj/math.o"
.importobj "obj/menu.o"
.importobj "obj/threads.o"
.importobj "obj/timer.o"
.importobj "obj/yellow_block.o"
.include "asm/hooks.s"
.close //close file
