//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/ct2JP.z64", "rom/ct2JP.mod.z64", 0 // Open the ROM file
.include "asm/symbols.asm" // Include ct2.asm to tell armips' linker where to find the game's function(s)
.include "asm/bootPatch.asm"
.include "asm/patches.asm"
.include "asm/hooks.s"
.importobj "obj/crash.o"
.importobj "obj/main.o"
.importobj "obj/math.o"
.close //close file
